#!/bin/sh
echo "COMMANDS:"
echo "record <trackname>"
echo "mix <trackname> <trackname>"
echo "overdub <trackname> <backingtrack>"
echo "playback <trackname>"
echo "list - show all tracks"
echo "remove <trackname>"
echo "bpm <new bpm>"
echo "quit - quits this prompt"
echo "? - prints this text"
